#!/bin/bash
# Quick script to add more photos from GitHub Issue #225

echo "🖼️  Add More Hardware Photos - Quick Guide"
echo "=========================================="
echo ""
echo "1. Opening GitHub issue in browser..."
open "https://github.com/geerlingguy/mini-rack/issues/225"
echo ""
echo "2. Right-click on each image and select 'Save Image As...'"
echo "3. Save to: $(pwd)/public/"
echo ""
echo "Recommended photos to download (5-7 additional photos):"
echo "  📸 rack-hero.jpeg       - Main assembled rack (hero shot)"
echo "  📸 rack-front.jpeg      - Front panel detail"
echo "  📸 rack-side.jpeg       - Side perspective"
echo "  📸 rack-internal.jpeg   - Internal architecture"
echo "  📸 rack-cooling.jpeg    - Cooling system detail"
echo "  📸 rack-networking.jpeg - Network layer"
echo "  📸 rack-power.jpeg      - Power distribution"
echo ""
echo "4. After downloading, uncomment the photo entries in:"
echo "   src/pages/hardware.astro (lines ~82-117)"
echo ""
echo "5. Build and deploy:"
echo "   npm run build && wrangler deploy"
echo ""
echo "The lightbox and descriptions are already coded and ready! 🚀"
